/**
 * 常见报错排查数据
 * 来源：mini-spring 仓库两个模块的实际构建/运行问题整理
 */

export interface ErrorEntry {
  /** 报错现象 / 关键词 */
  symptom: { zh: string; en: string }
  /** 产生原因 */
  cause: { zh: string; en: string }
  /** 解决方式 */
  fix: { zh: string; en: string }
  /** 标签：所属模块或场景 */
  tag: { zh: string; en: string }
}

export const errors: ErrorEntry[] = [
  {
    symptom: { zh: '编译报错：找不到符号', en: 'Cannot find symbol' },
    cause: {
      zh: 'Lombok 未启用，@Data / @Slf4j 生成的方法不存在',
      en: 'Lombok is not enabled, so methods generated by @Data / @Slf4j are missing',
    },
    fix: {
      zh: '在 IDE 中开启注解处理（Annotation Processing）并重新加载 Maven 工程',
      en: 'Enable Annotation Processing in the IDE and reload the Maven project',
    },
    tag: { zh: '构建', en: 'Build' },
  },
  {
    symptom: { zh: '测试失败：无法解析 classpath:spring.xml', en: 'Cannot resolve classpath:spring.xml' },
    cause: {
      zh: 'XML 配置没有放在资源根目录，或模块未被打包进测试 classpath',
      en: 'The XML config is not under the resource root, or the module is not on the test classpath',
    },
    fix: {
      zh: '把配置文件放到 src/main/resources 下，并用 mvn test -pl <module> 指定模块',
      en: 'Place the config under src/main/resources and target the module with mvn test -pl <module>',
    },
    tag: { zh: '配置', en: 'Config' },
  },
  {
    symptom: { zh: '运行时 NoSuchMethodError', en: 'NoSuchMethodError at runtime' },
    cause: {
      zh: 'servlet-api 版本与容器冲突，被以 compile 作用域重复引入',
      en: 'A conflicting servlet-api version is pulled in with compile scope',
    },
    fix: {
      zh: '把 servlet-api 依赖改为 provided 作用域，避免与运行环境重复',
      en: 'Change the servlet-api dependency to provided scope to avoid duplication',
    },
    tag: { zh: '依赖', en: 'Dependency' },
  },
  {
    symptom: { zh: '测试卡死不返回', en: 'Test hangs and never returns' },
    cause: {
      zh: '循环依赖没有走三级缓存，两个 Bean 互相等待实例化',
      en: 'Circular dependency does not go through the three-level cache, so both beans wait forever',
    },
    fix: {
      zh: '确认 addSingletonFactory 在属性填充前调用，且 getEarlyBeanReference 能返回半成品',
      en: 'Ensure addSingletonFactory runs before population and getEarlyBeanReference can return the early reference',
    },
    tag: { zh: 'IoC', en: 'IoC' },
  },
  {
    symptom: { zh: '代理类转换失败 ClassCastException', en: 'ClassCastException on a proxy' },
    cause: {
      zh: '目标类没有实现接口，JDK 动态代理无法生成同类型代理',
      en: 'The target class implements no interface, so the JDK proxy cannot match its type',
    },
    fix: {
      zh: '改用 CGLIB 代理（ProxyFactory 会自动降级），或为目标类抽取接口',
      en: 'Use a CGLIB proxy (ProxyFactory downgrades automatically), or extract an interface',
    },
    tag: { zh: 'AOP', en: 'AOP' },
  },
  {
    symptom: { zh: 'NoSuchBeanDefinitionException', en: 'NoSuchBeanDefinitionException' },
    cause: {
      zh: '类没有被扫描到：缺少 @Component，或不在扫描的包路径内',
      en: 'The class was not scanned: missing @Component, or outside the scanned package',
    },
    fix: {
      zh: '为类补上构造型注解，并确认扫描的 basePackage 覆盖到它',
      en: 'Add a stereotype annotation and make sure the scanned basePackage covers it',
    },
    tag: { zh: '容器', en: 'Container' },
  },
  {
    symptom: { zh: 'XML 解析异常：无法找到 DTD', en: 'XML parse error: DTD not found' },
    cause: {
      zh: 'beans 命名空间或 schemaLocation 缺失 / 拼写错误',
      en: 'The beans namespace or schemaLocation is missing or misspelled',
    },
    fix: {
      zh: '补全 <beans> 上的 xmlns 与 xsi:schemaLocation 声明',
      en: 'Complete the xmlns and xsi:schemaLocation declarations on <beans>',
    },
    tag: { zh: '配置', en: 'Config' },
  },
  {
    symptom: { zh: 'BeanNotOfRequiredTypeException', en: 'BeanNotOfRequiredTypeException' },
    cause: {
      zh: 'getBean 指定的类型与实际注册的 Bean 类型不一致',
      en: 'The type passed to getBean does not match the registered bean type',
    },
    fix: {
      zh: '用 getBean(name, Type.class) 双重定位，或检查是否存在同名 Bean 覆盖',
      en: 'Use getBean(name, Type.class) to pin both, and check for same-name overrides',
    },
    tag: { zh: '容器', en: 'Container' },
  },
]
